### GATEWAY

### Get all albums (via Gateway)
GET http://localhost:8080/api/albums

### Get specific album (via Gateway)
GET http://localhost:8080/api/albums/1e0cbdc4-22d5-4cdc-85ee-62af69a6f298

### Create new album (viaa Gateway)
POST http://localhost:8080/api/albums
Content-Type: application/json

{
  "title": "Anthem for the Underdog",
  "artist": "12 Stones",
  "releaseYear": 2007
}

### Update album (via Gateway)
PUT http://localhost:8080/api/albums/c94fecea-3f2c-4e83-9317-4a569437729a
Content-Type: application/json

{
  "title": "Anthem for the Underdog (Bonus Track Version)",
  "artist": "12 Stones",
  "releaseYear": 2007
}

### Delete album - will trigger event to delete songs (via Gateway)
DELETE http://localhost:8080/api/albums/1e0cbdc4-22d5-4cdc-85ee-62af69a6f298

### Get all songs from all albums (via Gateway)
GET http://localhost:8080/api/songs

### Get songs from specific album (via Gateway)
GET http://localhost:8080/api/albums/1e0cbdc4-22d5-4cdc-85ee-62af69a6f298/songs

### Get specific song from album (via Gateway)
GET http://localhost:8080/api/albums/c3d79e34-9281-49b7-85ec-d8d2a949cb82/songs/bef1379b-1669-450f-ae04-c4255ee58e10

### Create song in album (via Gateway)
POST http://localhost:8080/api/albums/c3d79e34-9281-49b7-85ec-d8d2a949cb82/songs
Content-Type: application/json

{
  "title": "Lie to Me",
  "durationMinutes": 3
}

### Update song (via Gateway)
PUT http://localhost:8080/api/albums/c3d79e34-9281-49b7-85ec-d8d2a949cb82/songs/bef1379b-1669-450f-ae04-c4255ee58e10
Content-Type: application/json

{
  "title": "Lie to Me (acoustic)",
  "durationMinutes": 3
}

### Delete song (via Gateway)
DELETE http://localhost:8080/api/albums/8964f681-24c8-42bf-bc02-0caf420b7a2a/songs/228db286-dccb-4ef1-bbfd-2aca521e49e7
### Test: Get songs from non-existent album (via Gateway)
GET http://localhost:8080/api/albums/00000000-0000-0000-0000-000000000000/songs

### Test: Create song in non-existent album (via Gateway)
POST http://localhost:8080/api/albums/00000000-0000-0000-0000-000000000000/songs
Content-Type: application/json

{
  "title": "Test Song",
  "durationMinutes": 3
}


### DIRECT

### Direct: Get all albums (Album Service - Port 8081)
GET http://localhost:8081/api/albums

### Direct: Get all songs (Song Service - Port 8082)
GET http://localhost:8082/api/songs